### ISSUE TITLE
文件POST上传

### ISSUE THREAD

**Issue by Cjiio** [kongzue/BaseOkHttpV3#11]
貌似好像不支持自定义文件后缀的上传,如.wld,上传报错空指针

**Comment by kongzue** [comment]
请确认该格式存在正确的MIME，因为post上传是需要获取到MIME type的，这个过程默认由BaseOkHttpV3代理获取，但若不是已知的MIME则可能出现问题

**Comment by Cjiio** [comment]
非已知MIME,为自定义后缀,请问如何解决

**Comment by fyqdcj123** [comment]
`2021-03-06 23:58:38.573 30737-30737/com.ygink.cn I/>>>: addRequestInfo: RequestInfo{url='http://xxx/api.php?app=10000&act=upload', parameter='bz=备注&cdname=名称&file=/storage/emulated/0/alipay/Headrush.wld&token=1357c52dbeace018aa8800bd8c3e70b8&type=bak'}
2021-03-06 23:58:38.576 30737-30985/com.ygink.cn E/>>>: 请求创建失败:http://xxx/api.php?app=10000&act=upload
2021-03-06 23:58:38.576 30737-30985/com.ygink.cn E/>>>: 参数:
2021-03-06 23:58:38.576 30737-30985/com.ygink.cn E/>>>>>>: bz=备注&cdname=名称&file=/storage/emulated/0/alipay/Headrush.wld&token=1357c52dbeace018aa8800bd8c3e70b8&type=bak
2021-03-06 23:58:38.576 30737-30985/com.ygink.cn E/>>>: 错误:java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
        at com.kongzue.baseokhttp.HttpRequest.getMimeType(HttpRequest.java:731)
        at com.kongzue.baseokhttp.HttpRequest.send(HttpRequest.java:373)
        at com.kongzue.baseokhttp.HttpRequest.doPost(HttpRequest.java:1219)
        at com.ygink.cn.activity.MainActivity2.onActivityResult(MainActivity2.java:94)
        at android.app.Activity.dispatchActivityResult(Activity.java:8249)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4931)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4979)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
2021-03-06 23:58:38.576 30737-30985/com.ygink.cn E/>>>: =====================================`

**Comment by fyqdcj123** [comment]
HttpRequest 731        `if (type != null || !type.isEmpty()) {`

**Comment by Cjiio** [comment]
```
    public static String getMimeType(File file) {
        String suffix = getSuffix(file);
        if (suffix == null) {
            return "file/*";
        }
        String type = MimeTypeMap.getSingleton().getMimeTypeFromExtension(suffix);
        if (type != null || !type.isEmpty()) {
            return type;
        }
        return "file/*";
    }
```
